import type { Metadata } from "next";

import "./globals.css";
import { inter, roboto } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
